package shadowfox.botanicaladdons.common.lib

object LibNames {
    val PRIESTLY_EMBLEM = "priestEmblem"
    val HOLY_SYMBOL = "holySymbol"
    val SPELL_ICON = "spellIcon"
    val SPELL_FOCUS = "spellFocus"
    val MJOLNIR = "mjolnir"
    val DAGGER = "dagger"
    val APPLE = "appleImmortality"
    val FATE_HORN = "fateHorn"
    val MORTAL_STONE = "mortalStone"
    val IRIDESCENT_DYE = "irisDye"
    val IRIDESCENT_DYE_AWAKENED = "irisDyeAwakened"
    val INFINITE_DYE = "dyeShard"
    val TOOLBELT = "toolbelt"
    val TRAVEL_STONE = "travelStone"
    val LIGHT_PLACER = "prismRod"
    val THUNDERFIST = "thunderFist"
    val FINDER = "findStone"
    val RESOURCE = "resource"
    val FOODBELT = "foodbelt"

    val SPELL_LEAP = "leap"
    val SPELL_INTERDICT = "interdict"
    val SPELL_PUSH = "push"
    val SPELL_LIGHTNING = "lightning"
    val SPELL_STRENGTH = "strength"
    val SPELL_PULL = "pull"
    val SPELL_RAINBOW = "iridescence"
    val SPELL_SPHERE = "bifrostWave"
    val SPELL_PROTECTION = "ironroot"
    val SPELL_IDUNN_INFUSION = "lifeInfusion"
    val SPELL_THOR_INFUSION = "lightningInfusion"
    val SPELL_NJORD_INFUSION = "njordInfusion"


    val AWAKENER = "divineCore"
    val STAR = "star"
    val PRISM_FLAME = "prismFlame"
    val IRIS_DIRT = "irisDirt"
    val RAINBOW_DIRT = "rainbowDirt"
    val IRIS_LOG = "irisLog"
    val RAINBOW_LOG = "rainbowLog"
    val IRIS_LEAVES = "irisLeaves"
    val RAINBOW_LEAVES = "rainbowLeaves"
    val IRIS_SAPLING = "irisSapling"
    val ALT_LOG = "altLog"
    val ALT_LEAVES = "altLeaves"
    val ALT_PLANKS = "altPlanks"

    val FAITHLESSNESS = "faithlessness"
    val DRAB_VISION = "drab"
    val ROOTED = "rooted"
    val OVERCHARGED = "overcharged"
    val FEATHERWEIGHT = "featherweight"
    val IMMORTALITY = "immortality"

    val HEAVY = "heavy"
    val LIGHT = "light"
}
